name: localization_helper
description: "AI Localization Assistant"
publish_to: 'none' 

version: 0.8.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  asset_icon: ^1.0.0
  auto_size_text: 
  cherry_toast: 
  file_picker: 
  flutter:
    sdk: flutter

  flutter_color_utils: ^0.0.1
  google_generative_ai: 
  http: 
  loader_overlay: ^5.0.0
  localization_lite: ^1.0.10
  provider: 
  shared_preferences: 
  toastification: ^3.0.2
  url_launcher: ^6.3.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 
  msix: ^3.16.8
  rename_app: ^1.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/localization/

msix_config:
  display_name: Treefy
  publisher_display_name: Hcody
  identity_name: hcody.hesham.treefy
  msix_version: 0.8.1.0
  logo_path: C:\Users\hcody\Downloads\treefyLogo.png
  capabilities: internetClient,